# Generated by Django 3.2.15 on 2022-08-27 23:08

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='posts.base')),
                ('post_body', models.TextField(max_length=500)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='post_body', unique_with=('author',))),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('edited', models.BooleanField(default=False)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Posted')], default=1)),
                ('is_shared', models.BooleanField(default=False)),
                ('angry_likes', models.ManyToManyField(blank=True, related_name='angry_likes', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('heart_likes', models.ManyToManyField(blank=True, related_name='heart_likes', to=settings.AUTH_USER_MODEL)),
                ('laugh_likes', models.ManyToManyField(blank=True, related_name='laugh_likes', to=settings.AUTH_USER_MODEL)),
                ('post_shared', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_posts', to='posts.post')),
                ('thumbs_likes', models.ManyToManyField(blank=True, related_name='thumb_likes', to=settings.AUTH_USER_MODEL)),
                ('total_likes', models.ManyToManyField(blank=True, related_name='post_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
            bases=('posts.base',),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='posts.base')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='post_name', unique_with=('name',))),
                ('email', models.EmailField(max_length=254)),
                ('content', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=True)),
                ('angry_likes', models.ManyToManyField(blank=True, related_name='comment_angry_likes', to=settings.AUTH_USER_MODEL)),
                ('heart_likes', models.ManyToManyField(blank=True, related_name='comment_heart_likes', to=settings.AUTH_USER_MODEL)),
                ('laugh_likes', models.ManyToManyField(blank=True, related_name='comment_laugh_likes', to=settings.AUTH_USER_MODEL)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('post_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.post')),
                ('thumbs_likes', models.ManyToManyField(blank=True, related_name='comment_thumb_likes', to=settings.AUTH_USER_MODEL)),
                ('total_likes', models.ManyToManyField(blank=True, related_name='comment_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
            bases=('posts.base',),
        ),
    ]
