# Generated by Django 3.2.15 on 2022-08-21 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='contributer',
            new_name='contributor',
        ),
    ]
