# Generated by Django 3.2.15 on 2022-08-22 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_contributer_comment_contributor'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='shared',
            field=models.BooleanField(default=False),
        ),
    ]
