# Generated by Django 3.2.15 on 2022-08-04 13:37

import autoslug.fields
import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.CharField(max_length=320, unique=True)),
                ('d_o_b', models.DateField(blank=True, null=True)),
                ('avatar', cloudinary.models.CloudinaryField(blank=True, default='/static/img/default-profile-image.png', max_length=255, null=True, verbose_name='avatar')),
                ('bio', models.TextField(max_length=800)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL), unique=True)),
                ('friends', models.ManyToManyField(blank=True, related_name='_profiles_profile_friends_+', to='profiles.Profile')),
                ('posts', models.ManyToManyField(related_name='posts', to='posts.Post')),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
