# Generated by Django 3.2.14 on 2022-08-02 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_slug',
            new_name='slug',
        ),
    ]
