# Generated by Django 3.2.15 on 2022-08-09 11:20

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='background',
            field=cloudinary.models.CloudinaryField(blank=True, default='/static/img/default_backgrounds/bg-four.jpg', max_length=255, null=True, verbose_name='background'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, default='/static/img/default-profile-img.png', max_length=255, null=True, verbose_name='avatar'),
        ),
    ]
