# Generated by Django 3.2.15 on 2022-08-09 11:50

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20220809_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, default='/static/img/default-profile-image.png', max_length=255, null=True, verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='background',
            field=cloudinary.models.CloudinaryField(blank=True, default='/static/img/default-backgrounds/bg.jpg', max_length=255, null=True, verbose_name='background'),
        ),
    ]
