# Generated by Django 3.2.15 on 2022-08-09 11:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20220809_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='background',
            field=cloudinary.models.CloudinaryField(blank=True, default='/static/img/default_backgrounds/bg.jpg', max_length=255, null=True, verbose_name='background'),
        ),
    ]
