# Generated by Django 3.2.15 on 2022-08-17 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_bar', '0003_alter_search_searches'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Search',
        ),
    ]
