# Generated by Django 3.2.15 on 2022-08-20 16:28

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('django_messages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='body',
            field=django_cryptography.fields.encrypt(models.TextField(max_length=1400, verbose_name='Body')),
        ),
        migrations.AlterField(
            model_name='message',
            name='subject',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=100, verbose_name='Subject')),
        ),
    ]
